### ISSUE TITLE
Simbolen kunnen niet vanaf het beging gebruikt worden

### ISSUE THREAD

**Issue by dorusd** [visknut/GecorrumpeerdeFlamingo#1]
Wanneer je de symbolen direct probeert op te losen, geen hij aan dat dit niet juist is. Wanneer we de symbolen als laatste oploste ging dit echter prima. We konde in de handleiding niet vinen dat dit een ding is

**Comment by visknut** [comment]
Het kan zijn dat dit fout stond in de oude versie van de handleiding. De nieuwe versie is nu aan toegevoegd. 
Hierin staat: "Het input component dient altijd als laatste ontmanteld te worden."
