### ISSUE TITLE
Niet alle symbolen zijn altijd goed afgebeeld

### ISSUE THREAD

**Issue by dorusd** [visknut/GecorrumpeerdeFlamingo#2]
![image](https://github.com/visknut/GecorrumpeerdeFlamingo/assets/16864022/acdb2718-8245-4690-8856-d1e729be5aa9)

**Comment by visknut** [comment]
Niet alle fonts zijn ondersteund. Ik heb een lijstje met geteste fonts toegevoegd aan de readme.md.
